### PR TITLE
fix: (ell_complex.rst.txt) example code

### PR DESCRIPTION
**Pull request by notdp**
AttributeError: 'list' object has no attribute 'title'

### CODE REVIEW

**Comment by MadcowD** [comment]
The parse API is a future API so I've been changing it quite a bit. If there are multiple parts, objects in the message, then parsed is a list. Otherwise it's a single object as a VO04. 

pip install --upgrade ell-ai

**Comment by MadcowD** [comment]
It may actually be a bad thing in the long run, but as far as I see it,
this API really hasn’t settled yet for ai providers

**Comment by notdp** [comment]
Thank you for your help with this issue.

 I have a follow-up question regarding the return types:  

I noticed that after applying the **complex** decorator, the return object could be either **List[Message]** or **Message**. 
Could you please clarify under what circumstances a language model would respond with **List[Message]**? Is this similar to scenarios where some AI chatbots provide multiple answer options and ask the user to rate them?  


Thank you for your time and assistance!

**Comment by notdp** [comment]
image

I understand now, the result is determined by the parameter **n** when calling the model, 
thank you!

**Pull request closed without merging**
