### PR TITLE
Add OpenRouter Provider  for Enhanced Integration

### PR DESCRIPTION
**Pull request by nmehran**
Introducing support for OpenRouter, which provides extensive access to multiple AI models, lowers the barrier to entry for developers and significantly expands the audience .

### Summary of Changes:
- **Provider Structure Update**: Added `OpenRouterProvider` and `OpenRouter` client to allow integration various features specific to OpenRouter.
- **Client Attributes**:  Implemented used_models, global_stats, and provider_preferences attributes in the OpenRouter client to track model usage, costs, and user preferences.
- **Example Updates**: Modified `openrouter_example.py` to demonstrate correct client usage and reflect the OpenRouter specific API features.
- **Testing Enhancements**: Added tests using `pytest` fixtures and mocked clients for increased reliability in interactions with OpenRouter.

### Related Issues:
- **Issue #222**: Addresses compatibility issues that arose after updating to version 0.0.7, resolving API key authentication errors.
- **Issue #56**: Supports the integration of various LLM providers, enhancing accessibility for users of the OpenRouter framework.

### Caveats:
- I did not conduct an extensive review of the entire codebase, so there may be unforeseen issues or areas that require further attention.
- Please test thoroughly to ensure compatibility and functionality in your specific use cases.
- The implementation structure may not align with my preferred design choices; however, I opted for a minimally intrusive approach to the current codebase to ease integration.

### Usage Example:
```python
or_client = openrouter.Client(
    api_key=os.getenv("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1",
)
or_model = "qwen/qwen-2.5-72b-instruct"

@ell.simple(model=or_model, client=or_client)
def generate_movie_review_or(movie: str):
    """You are a movie review generator. Given the name of a movie, you need to return a structured review."""
    return f"generate a review for the movie {movie}"
```

I hope this implementation serves as a decent baseline that accelerates the integration of OpenRouter support and provides a foundation for further enhancements.  Discussion, feedback and suggestions for improvements are welcome as we integrate OpenRouter support.

### CODE REVIEW

**Comment by nmehran** [comment]
### Update on PR: Add OpenRouter Provider for Enhanced Integration #229

Refactored OpenRouter integration to inherit `OpenAIClient` and `OpenAIProvider`, simplifying the codebase and removing obsolete components.

**Refactor Summary:**
- **Inheritance Structure**: The `OpenRouter` class now inherits from `OpenAIClient`, and the `OpenRouterProvider` inherits from `OpenAIProvider`, leveraging existing functionality and reducing redundancy.
- **Removed Obsolete Tests**: Deleted the `test_openrouter_provider.py` file, as its tests are no longer relevant with the new structure.
- **Code Simplification**: Eliminated unnecessary methods, resulting in cleaner and more maintainable client code.
- **Lost Functionality**: The refactor removed support for asynchronous retrieval of generation stats and non-standard generation information by default.  I believe this aligns closer to the project's goals.

**Comment by MadcowD** [comment]
Can you explain why we need an OpenRouter provider, I thought it was all OpenAI compatible and you only needed an openrouter client?

**Comment by nmehran** [comment]
Actually, you have a point, we can do this entirely without any additional provider or client in a dozen or so lines of code:

```python
from openai import OpenAI

openrouter_client = OpenAI(
    api_key=os.getenv("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1",
)

openrouter_model = "meta-llama/llama-3.1-8b-instruct"
ell.config.register_model(openrouter_model, openrouter_client)

provider_prefs = {
    "allow_fallbacks": False,
    "data_collection": "deny",
    "order": ["Hyperbolic", "Together"],
    "ignore": ["Fireworks"],
    "quantizations": ["bf16", "fp8"]
}

@ell.simple(model=openrouter_model, client=openrouter_client, extra_body={"provider": provider_prefs})
def generate_greeting(name: str) -> str:
    """You are a friendly AI assistant."""
    return f"Generate a warm, concise greeting for {name}"

def multiple_preferences_example():
    print("\n--- Example: Multiple Provider Preferences ---")
    greeting = generate_greeting("Mark Zuckerberg")
    print(f"Multiple Preferences Example Greeting: {greeting}")
```

The secret is passing the `extra_body` dictionary to `api_params`.

If you take a look at the example file, `openrouter_ex.py`, the only benefit would be the improved client API catered to OpenRouter, how we pass OpenRouter-specific preferences, and post-processing of metadata statistics.

Whether we should ignore the OpenRouter-specific processing of metadata in the OpenRouterProvider, or whether we should maintain templates such as `ProviderPreferences`,  methods such as `get_model_parameters`, `get_generation_data`, and the registering of all OpenRouter models is completely optional and entirely up to you.

At a minimum, we could add an  `openrouter_ex.py` demonstrating usage with the OpenAI client.  

Glad to be part of this discussion.

**Comment by MadcowD** [comment]
These are really thoughtful points. I'm inclined to just have an openrouter_ex.py file where you pass extra body for fallbacks, though I understand if this isn't ideal. Also you shouldn't nee to register the model unless you don't want to drag the client around :) 


```python
from openai import OpenAI

openrouter_client = OpenAI(
    api_key=os.getenv("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1",
)

extra_body = dict(provider={
    "allow_fallbacks": False,
    "data_collection": "deny",
    "order": ["Hyperbolic", "Together"],
    "ignore": ["Fireworks"],
    "quantizations": ["bf16", "fp8"]
})

@ell.simple(model="meta-llama/llama-3.1-8b-instruct, client=openrouter_client, extra_body=extra_body)
def generate_greeting(name: str) -> str:
    """You are a friendly AI assistant."""
    return f"Generate a warm, concise greeting for {name}"

def multiple_preferences_example():
    print("\n--- Example: Multiple Provider Preferences ---")
    greeting = generate_greeting("Mark Zuckerberg")
    print(f"Multiple Preferences Example Greeting: {greeting}")
```

Is sufficient. I suppose you would want to always pass things like 
```
  "allow_fallbacks": False,
    "data_collection": "deny",
```
to all calls though then this is painful, perhaps (`custom_query`) on the python client. I have to say it could even be excessive though, even openrouter's own documentation suggest using extra body:
```
from openai import OpenAI
from os import getenv

# gets API Key from environment variable OPENAI_API_KEY
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=getenv("OPENROUTER_API_KEY"),
)

completion = client.chat.completions.create(
  extra_headers={
    "HTTP-Referer": $YOUR_SITE_URL, # Optional, for including your app on openrouter.ai rankings.
    "X-Title": $YOUR_APP_NAME, # Optional. Shows in rankings on openrouter.ai.
  },
  # pass extra_body to access OpenRouter-only arguments.
  extra_body={
    "model": "openai/gpt-4o",
    # when openai/gpt-4o fails, mixtral is used as a fallback.
    # "models": [
    #   "openai/gpt-4o",
    #   "mistralai/mixtral-8x22b-instruct"
    # ]
  },
  messages=[
    {
      "role": "user",
      "content": "Say this is a test",
    },
  ],
)
print(completion.choices[0].message.content)
```

Here's what we could do:
* We can add an openrouter_ex.py with this minimal example.
* You could publish an `ell-openrouter` package on pypi that registers all models automatically & registers a provider. We can link to it in the official documentation. **this is my goal with ell is that people use it like a library and make a lot of packages on top of it!**

**Comment by MadcowD** [comment]
Is it unfair that I have a `groq` provider and not a `openrouter`?

**Comment by nmehran** [comment]
I like the idea of an `ell-openrouter` package.  Perhaps, we could even take things further and move all providers to an `ell-providers` package, as they are not the main focus of the project, while taking a bit of extra maintenance.  The `ell-providers` package could then define various providers, the providers' clients, templates, and mappings, if any.

With regard to always passing the `extra_body` parameter, I would view that as an intermediate solution, but definitely a decent immediate workaround.  The current PR attempted to resolve this by making preferences optionally stateful with the `openrouter_client.set_provider_preferences` method and then doing some pre-processing in the `OpenRouterProvider` class.

All in all, I think the `openrouter_ex.py` with the minimal example and some documentation with regard to passing `extra_body` arguments (not just OpenRouter cases, but generally as well) is a great step, and moving toward separating the provider logic from the language framework is a good solution for maintainability.

P.S. Good point about not having to register the model with ell, I did not know that :)

**Comment by MadcowD** [comment]
Would you be willing to refactor the PR to only have openrouter_ex?

**Comment by nmehran** [comment]
The PR now focuses solely on providing a minimal example in openrouter_ex.py, demonstrating how to use OpenRouter with the standard OpenAI client. This approach aligns with your suggestion and should provide a cleaner, more maintainable solution for users who want to utilize OpenRouter within the ell framework.
Please review the changes and let me know if any further adjustments are needed.

**Comment by MadcowD** [comment]
Amazing <3 Thank you so much :) Will revisit if there's enough demand otherwise I encourage you to make a package :D

**Pull request merged**
